import { createClient } from '@/lib/supabase/server'
import Link from 'next/link'
const naira = (amount: number) => `₦${amount.toLocaleString()}`
type House = { id: string; address: string }
type AccessLog = { id: string; direction: string; scanned_at: string; residents: { full_name: string }[] }
export default async function AdminDashboard() {
  const supabase = await createClient()
  const { data: invoices } = await supabase.from('invoices').select('id, amount, amount_paid, status, houses ( id, address )')
  const { data: accessLogsToday } = await supabase.from('access_logs').select('id, direction, scanned_at, residents ( full_name )').gte('scanned_at', new Date().toISOString().slice(0, 10)).order('scanned_at', { ascending: false }).limit(5)
  const byHouse: Record<string, { address: string; owed: number; paid: number }> = {}
  for (const inv of invoices ?? []) { const house = inv.houses as unknown as House | null; if (!house) continue; byHouse[house.id] ??= { address: house.address, owed: 0, paid: 0 }; byHouse[house.id].owed += Number(inv.amount); byHouse[house.id].paid += Number(inv.amount_paid ?? 0) }
  const houseList = Object.values(byHouse); const owing = houseList.filter((h) => h.paid < h.owed).sort((a,b) => (b.owed-b.paid)-(a.owed-a.paid)).slice(0,5); const totalOwed = houseList.reduce((sum,h)=>sum+h.owed,0); const totalPaid = houseList.reduce((sum,h)=>sum+h.paid,0); const outstanding = totalOwed-totalPaid
  return <div className="page-wrap"><div className="dashboard-header"><div><span className="eyebrow">Operations dashboard</span><h1 className="page-title">Good morning, Ada.</h1><p className="page-lead">Here’s the financial and gate activity snapshot for Evergreen Estate.</p></div><div className="header-actions"><Link href="/admin/residents/new" className="action secondary">Add resident</Link><Link href="/admin/invoices/generate" className="action">Generate dues <span aria-hidden="true">→</span></Link></div></div><section className="metrics" aria-label="Estate billing summary"><article className="metric featured"><span className="metric-label">Estate billed</span><strong className="metric-value">{naira(totalOwed)}</strong><p className="metric-note">Across {houseList.length} homes this period</p></article><article className="metric"><span className="metric-label">Collected</span><strong className="metric-value">{naira(totalPaid)}</strong><p className="metric-note"><span className="trend">↑ On track</span> with your collection target</p></article><article className="metric"><span className="metric-label">Outstanding</span><strong className="metric-value red">{naira(outstanding)}</strong><p className="metric-note">{owing.length} homes need a gentle follow-up</p></article></section><section className="dashboard-grid"><article className="panel"><div className="panel-head"><h2>Balances needing attention</h2><Link href="/admin/residents">View residents →</Link></div><div className="panel-body">{owing.length ? owing.map((h) => <div className="house-row" key={h.address}><div><strong>{h.address}</strong><span>{naira(h.paid)} paid of {naira(h.owed)}</span></div><div><span className="pill">Outstanding</span></div><div className="amount red">{naira(h.owed-h.paid)}</div></div>) : <p className="empty">Nothing is outstanding. Your estate is all caught up.</p>}</div></article><article className="panel"><div className="panel-head"><h2>Today at the gate</h2><Link href="/admin/access-logs">All activity →</Link></div><div className="panel-body">{accessLogsToday?.length ? accessLogsToday.map((log: AccessLog) => <div className="activity" key={log.id}><span className={`activity-symbol ${log.direction === 'exit' ? 'exit' : ''}`} aria-hidden="true">{log.direction === 'exit' ? '↗' : '↘'}</span><div><strong>{log.residents?.[0]?.full_name ?? 'Unknown resident'}</strong><small>{log.direction === 'exit' ? 'Exited' : 'Entered'} · {new Date(log.scanned_at).toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'})}</small></div></div>) : <p className="empty">No gate scans have been recorded today.</p>}</div></article></section></div>
}
