'use client'
import {useEffect,useState} from 'react'
import {createClient} from '@/lib/supabase/client'
import type {GateDueDetails} from '@/lib/gate-due-emails'
type Alert={id:string;details:GateDueDetails;gate_due_emails:{status:string}[]}
export function GateDueAlerts(){
 const[alerts,setAlerts]=useState<Alert[]>([]),[error,setError]=useState(''),[loaded,setLoaded]=useState(false)
 useEffect(()=>{let active=true;const db=createClient();const refresh=async()=>{const{data,error}=await db.from('gate_due_alerts').select('id,details,gate_due_emails(status)').order('created_at',{ascending:false}).limit(20);if(active){setLoaded(true);setError(error?'Gate dues alerts could not be loaded. Check that the gate-alert migration has been applied.':'');if(data)setAlerts(data as unknown as Alert[])}};void refresh();const timer=setInterval(()=>void refresh(),30000);return()=>{active=false;clearInterval(timer)}},[])
 return <section className="panel mb-6" aria-label="Unpaid dues entry alerts"><div className="panel-head"><h2>Unpaid-dues entry alerts</h2><span className="text-xs">Latest 20 · updates every 30 seconds</span></div><div className="p-4">{error?<p role="alert">{error}</p>:!loaded?<p role="status">Loading entry alerts…</p>:!alerts.length?<p>No unpaid-dues entry alerts.</p>:alerts.map(alert=><article key={alert.id} className="border-b py-4"><strong>{alert.details.name} entered the estate</strong><p className="text-sm">{alert.details.address} · {new Date(alert.details.entered_at).toLocaleString('en-GB',{timeZone:'Africa/Lagos'})} WAT</p><p className="text-sm">Household balance at entry: <strong className="red">₦{Number(alert.details.balance).toLocaleString('en-NG',{minimumFractionDigits:2})}</strong></p><p className="text-sm">{alert.details.email||'No resident email'} · {alert.details.phone||'No phone'}</p><p className="text-xs text-gray-500">Emails accepted by provider: {alert.gate_due_emails.filter(e=>e.status==='sent').length}; queued: {alert.gate_due_emails.filter(e=>['pending','sending'].includes(e.status)).length}; needs review: {alert.gate_due_emails.filter(e=>e.status==='failed').length}. Acceptance does not confirm inbox delivery.</p></article>)}</div></section>
}
